# Generated by Django 2.1.3 on 2019-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('username', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
                ('vmx_path', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
