# Generated by Django 2.1.3 on 2019-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmcservice', '0002_virtualmachine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(default='off', max_length=8),
        ),
    ]
