# Generated by Django 2.1.3 on 2019-06-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmcservice', '0003_virtualmachine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='operating_system',
            field=models.CharField(default='Ubuntu Server 18.04.2 LTS', max_length=128),
        ),
    ]
